---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Removing File Directories
      file:
        state: absent
        path: "{{ item }}"
      with_items:
          - /psa/var
          - /psa/data/psablitz
          - {{path.stdout}}/nzbget
          - {{path.stdout}}/sab
          - {{path.stdout}}/rutorrent
          - {{path.stdout}}/move
          - {{path.stdout}}/gcrypt
          - {{path.stdout}}/deluge
          - {{path.stdout}}/torrentvpn
          - {{path.stdout}}/qbittorrent
      ignore_errors: yes
