#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705 - Deiteq - Sub7Seven
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################

- name: Install CPUFrequtils
  apt:
    name:
    - cpufrequtils

########### Remove Governer Policy If Exists

- name: Removing File Directories
  file:
    state: absent
    path: /etc/default/cpufrequtils

########### Set Governer File

- name: CPUFrequtils Checker
  stat:
    path: /etc/default/cpufrequtils
  register: cpu

- name: Create /etc/default/cpufrequtils
  file:
    path: /etc/default/cpufrequtils
    state: touch
  when: cpu.stat.exists == False

########### Establish CPU Performance
## Three Modes With Menu Selection
## 1. Performance, 2. Ondemand, 3. Conservative

- name: CPU Performance = Performance
  lineinfile:
    path: "/etc/default/cpufrequtils"
    regexp: '^GOVENOR\s?='
    line: 'GOVENOR="ondemand"'
    state: present

- name: CPU Freq Set
  lineinfile:
    path: "/etc/default/cpufrequtils"
    regexp: '^GOVERNOR\s?='
    line: 'GOVERNOR="ondemand"'
    state: present

- name: Enable Governer
  lineinfile:
    path: "/etc/default/cpufrequtils"
    regexp: '^ENABLE\s?='
    line: 'ENABLE="true"'
    state: present

################### STOP SCALING

- name: Disable Scaling Frequency
  shell: "update-rc.d ondemand enable"
  when: (ansible_service_mgr != 'systemd')

- name: Disable Scaling Frequency UB18
  shell: "systemctl enable ondemand"
  when: (ansible_service_mgr == 'systemd')
