#!/bin/bash
#
# Title:      PSAutomate
# Based On:   PGBlitz (Reference Title File)
# Original Author(s):  Flicker-rate
# PSAutomate Auther: fattylewis
# URL:        https://psautomate.io - http://github.psautomate.io
# GNU:        General Public License v3.0
################################################################################

########### Check If Backup sysctl exists
- name: sysctl Checker
  stat:
    path: /psa/var/sysctl.conf
  register: sysctl

########### Backup Sysctl Config
- name: Backup Kernel Parameters
  copy:
    src: /etc/sysctl.conf
    dest: /psa/var/sysctl.conf
  when: sysctl.stat.exists == False

########### Reset Sysctl Config With Backup File
- name: Reseting Kernel Parameters
  copy:
    src: /psa/var/sysctl.conf
    dest: /etc/sysctl.conf
  when: sysctl.stat.exists == True

########### Adjust kernel params
# enable/disable tweaks with --skip-tags

#################### bbr
- name: Enable BBR TCP Congestion Control
  blockinfile:
    path: /etc/sysctl.conf
    marker: "# TCP BBR"
    block: |
      net.core.default_qdisc=fq
      net.ipv4.tcp_congestion_control=bbr
  tags:
    - bbr

- name: Seedboxer Kernel Tweaks
  blockinfile:
    path: /etc/sysctl.conf
    marker: "# Seedboxer"
    block: |
      fs.file-max = 2097152
      vm.swappiness = 10
      vm.dirty_ratio = 60
      vm.dirty_background_ratio = 2
      net.ipv4.tcp_synack_retries = 2
      net.ipv4.ip_local_port_range = 2000 65535
      net.ipv4.tcp_rfc1337 = 1
      net.ipv4.tcp_fin_timeout = 15
      net.ipv4.tcp_keepalive_time = 300
      net.ipv4.tcp_keepalive_probes = 5
      net.ipv4.tcp_keepalive_intvl = 15
      net.core.rmem_default = 31457280
      net.core.rmem_max = 12582912
      net.core.wmem_default = 31457280
      net.core.wmem_max = 12582912
      net.core.somaxconn = 4096
      net.core.netdev_max_backlog = 65536
      net.core.optmem_max = 25165824
      net.ipv4.tcp_mem = 65536 131072 262144
      net.ipv4.udp_mem = 65536 131072 262144
      net.ipv4.tcp_rmem = 8192 87380 16777216
      net.ipv4.udp_rmem_min = 16384
      net.ipv4.tcp_wmem = 8192 65536 16777216
      net.ipv4.udp_wmem_min = 16384
      net.ipv4.tcp_max_tw_buckets = 1440000
      net.ipv4.tcp_tw_recycle = 1
      net.ipv4.tcp_tw_reuse = 1
  tags:
    - seedboxer

#################### tj007s13
# https://www.reddit.com/r/seedboxes/comments/6spbla/my_linux_server_performance_tweaks/
- name: tj007s13's kernel tweaks
  blockinfile:
    path: /etc/sysctl.conf
    marker: "# tj007s13"
    block: |
      vm.swappiness = 1
      fs.file-max = 2000000
      kernel.pid_max = 4194303
      kernel.sched_migration_cost_ns = 5000000
      kernel.sched_autogroup_enabled = 0
      net.ipv4.tcp_slow_start_after_idle = 0
      net.ipv4.tcp_no_metrics_save = 0
      net.ipv4.tcp_abort_on_overflow = 0
      net.ipv4.tcp_window_scaling = 1
      net.ipv4.tcp_tw_reuse = 1
      vm.dirty_background_ratio = 20
      vm.dirty_ratio = 30
      net.ipv4.tcp_rfc1337 = 1
      net.ipv4.tcp_sack = 1
      net.ipv4.tcp_fack = 1
      net.ipv4.tcp_workaround_signed_windows = 1
      net.ipv4.tcp_timestamps = 1
      net.ipv4.tcp_syncookies = 1
      net.ipv4.tcp_syn_retries = 2
      net.ipv4.tcp_synack_retries = 2
      net.ipv4.tcp_orphan_retries = 2
      net.ipv4.tcp_retries2 = 8
      net.ipv4.ip_local_port_range = 1024 65535
      net.core.netdev_max_backlog = 3240000
      net.core.somaxconn = 50000
      net.ipv4.tcp_max_tw_buckets = 1440000
      net.ipv4.tcp_max_syn_backlog = 3240000
      net.ipv4.tcp_mtu_probing = 1
      net.ipv4.tcp_fin_timeout = 15
      net.ipv4.tcp_keepalive_time = 600
      net.ipv4.tcp_keepalive_intvl = 10
      net.ipv4.tcp_keepalive_probes = 9
      net.ipv4.ip_no_pmtu_disc = 0
      net.core.rmem_default = 16777216
      net.core.wmem_default = 16777216
      net.core.optmem_max = 16777216
      net.core.rmem_max = 16777216
      net.core.wmem_max = 16777216
      net.ipv4.tcp_fastopen = 3
      net.ipv4.tcp_rmem = 4096 87380 16777216
      net.ipv4.tcp_wmem = 4096 65536 16777216
      net.ipv4.tcp_adv_win_scale = 1
      net.core.default_qdisc = fq
      net.ipv4.tcp_congestion_control = bbr
  tags:
    - tj

#################### klaver.it
- name: Klaver.it Kernel Tweaks
  blockinfile:
    path: /etc/sysctl.conf
    marker: "# Klaver"
    block: |
      net.ipv4.tcp_syncookies = 1
      net.ipv4.tcp_syn_retries = 2
      net.ipv4.tcp_synack_retries = 2
      net.ipv4.tcp_max_syn_backlog = 4096
      net.ipv4.ip_forward = 0
      net.ipv4.conf.all.forwarding = 0
      net.ipv4.conf.default.forwarding = 0
      net.ipv6.conf.all.forwarding = 0
      net.ipv6.conf.default.forwarding = 0
      net.ipv4.conf.all.send_redirects = 0
      net.ipv4.conf.default.send_redirects = 0
      net.ipv4.conf.all.accept_source_route = 0
      net.ipv4.conf.default.accept_source_route = 0
      net.ipv6.conf.all.accept_source_route = 0
      net.ipv6.conf.default.accept_source_route = 0
      net.ipv4.conf.all.rp_filter = 1
      net.ipv4.conf.default.rp_filter = 1
      net.ipv4.conf.all.accept_redirects = 0
      net.ipv4.conf.default.accept_redirects = 0
      net.ipv4.conf.all.secure_redirects = 0
      net.ipv4.conf.default.secure_redirects = 0
      net.ipv6.conf.all.accept_redirects = 0
      net.ipv6.conf.default.accept_redirects = 0
      net.ipv4.conf.all.log_martians = 1
      net.ipv4.conf.default.log_martians = 1
      net.ipv4.tcp_fin_timeout = 7
      net.ipv4.tcp_keepalive_time = 300
      net.ipv4.tcp_keepalive_probes = 5
      net.ipv4.tcp_keepalive_intvl = 15
      net.ipv4.conf.all.bootp_relay = 0
      net.ipv4.conf.all.proxy_arp = 0
      net.ipv4.tcp_timestamps = 1
      net.ipv4.icmp_echo_ignore_all = 0
      net.ipv4.icmp_echo_ignore_broadcasts = 1
      net.ipv4.icmp_ignore_bogus_error_responses = 1
      net.ipv4.ip_local_port_range = 16384 65535
      net.ipv4.tcp_rfc1337 = 1
      net.ipv4.tcp_window_scaling = 1
      net.ipv4.tcp_rmem = 8192 87380 16777216
      net.ipv4.udp_rmem_min = 16384
      net.core.rmem_default = 262144
      net.core.rmem_max = 16777216
      net.ipv4.tcp_wmem = 8192 65536 16777216
      net.ipv4.udp_wmem_min = 16384
      net.core.wmem_default = 262144
      net.core.wmem_max = 16777216
      net.core.somaxconn = 32768
      net.core.netdev_max_backlog = 16384
      net.core.dev_weight = 64
      net.core.optmem_max = 65535
      net.ipv4.tcp_max_tw_buckets = 1440000
      net.ipv4.tcp_tw_recycle = 0
      net.ipv4.tcp_tw_reuse = 1
      net.ipv4.tcp_max_orphans = 16384
      net.ipv4.tcp_orphan_retries = 0
      net.ipv4.ipfrag_high_thresh = 512000
      net.ipv4.ipfrag_low_thresh = 446464
      net.ipv4.tcp_no_metrics_save = 1
      net.ipv4.tcp_moderate_rcvbuf = 1
      net.unix.max_dgram_qlen = 50
      net.ipv4.neigh.default.gc_thresh3 = 2048
      net.ipv4.neigh.default.gc_thresh2 = 1024
      net.ipv4.neigh.default.gc_thresh1 = 32
      net.ipv4.neigh.default.gc_interval = 30
      net.ipv4.neigh.default.proxy_qlen = 96
      net.ipv4.neigh.default.unres_qlen = 6
      net.ipv4.tcp_retries2 = 15
      net.ipv4.tcp_retries1 = 3
      net.ipv4.tcp_slow_start_after_idle = 0
      net.ipv4.tcp_fastopen = 3
      net.ipv4.route.flush = 1
      fs.file-max = 209708
      vm.swappiness = 30
      vm.dirty_ratio = 30
      vm.dirty_background_ratio = 5
      vm.mmap_min_addr = 4096
      vm.overcommit_ratio = 50
      vm.overcommit_memory = 0
      kernel.shmmax = 268435456
      kernel.shmall = 268435456
      vm.min_free_kbytes = 65535
  tags:
    - klaver

################### Load Kernel Configs

- name: Apply Kernel Settings
  shell: "sysctl -e -p"
