---
- hosts: localhost
  gather_facts: false
  tasks:

    - name: "Cloning PSABlitz 0.2.0"
      git:
        repo: "https://github.com/psautomateio/Install.git"
        dest: "/psa/psastage"
        version: "0.2.0"
        force: yes
